/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// AdditionalInfo : Object which is contains brands and categories associated with this suggestion.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdditionalInfo {
    #[serde(rename = "brands")]
    pub brands: Vec<String>,
    #[serde(rename = "categories")]
    pub categories: Vec<String>,
}

impl AdditionalInfo {
    /// Object which is contains brands and categories associated with this suggestion.
    pub fn new(brands: Vec<String>, categories: Vec<String>) -> AdditionalInfo {
        AdditionalInfo {
            brands,
            categories,
        }
    }
}


