/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// AttributeSuggestion : Object with one single attribute and associated properties.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttributeSuggestion {
    /// Suggestion itself.
    #[serde(rename = "suggestions", skip_serializing_if = "Option::is_none")]
    pub suggestions: Option<Vec<String>>,
}

impl AttributeSuggestion {
    /// Object with one single attribute and associated properties.
    pub fn new() -> AttributeSuggestion {
        AttributeSuggestion {
            suggestions: None,
        }
    }
}


