/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// Audience : The target group associated with a given audience (e.g. male, veterans, car owners, musicians, etc.) of the product.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Audience {
    /// The genders of the audience. Strongly encouraged to use the standard values: 'male', 'female', 'unisex'. At most 5 values are allowed. Length limit of 128 characters.
    #[serde(rename = "genders", skip_serializing_if = "Option::is_none")]
    pub genders: Option<Vec<String>>,
    /// The age groups of the audience. Strongly encouraged to use the standard values: 'newborn' (up to 3 months old), 'infant' (3-12 months old), 'toddler' (1-5 years old), 'kids' (5-13 years old), 'adult' (typically teens or older). At most 5 values are allowed. Length limit of 128 characters.
    #[serde(rename = "ageGroups", skip_serializing_if = "Option::is_none")]
    pub age_groups: Option<Vec<String>>,
}

impl Audience {
    /// The target group associated with a given audience (e.g. male, veterans, car owners, musicians, etc.) of the product.
    pub fn new() -> Audience {
        Audience {
            genders: None,
            age_groups: None,
        }
    }
}


