/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// BiasDtoPeriodStrengthDto : The amount the bias will affect the search results.

/// The amount the bias will affect the search results.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BiasDtoPeriodStrengthDto {
    #[serde(rename = "ABSOLUTE_INCREASE")]
    AbsoluteIncrease,
    #[serde(rename = "STRONG_INCREASE")]
    StrongIncrease,
    #[serde(rename = "MEDIUM_INCREASE")]
    MediumIncrease,
    #[serde(rename = "WEAK_INCREASE")]
    WeakIncrease,
    #[serde(rename = "LEAVE_UNCHANGED")]
    LeaveUnchanged,
    #[serde(rename = "WEAK_DECREASE")]
    WeakDecrease,
    #[serde(rename = "MEDIUM_DECREASE")]
    MediumDecrease,
    #[serde(rename = "STRONG_DECREASE")]
    StrongDecrease,
    #[serde(rename = "ABSOLUTE_DECREASE")]
    AbsoluteDecrease,

}

impl ToString for BiasDtoPeriodStrengthDto {
    fn to_string(&self) -> String {
        match self {
            Self::AbsoluteIncrease => String::from("ABSOLUTE_INCREASE"),
            Self::StrongIncrease => String::from("STRONG_INCREASE"),
            Self::MediumIncrease => String::from("MEDIUM_INCREASE"),
            Self::WeakIncrease => String::from("WEAK_INCREASE"),
            Self::LeaveUnchanged => String::from("LEAVE_UNCHANGED"),
            Self::WeakDecrease => String::from("WEAK_DECREASE"),
            Self::MediumDecrease => String::from("MEDIUM_DECREASE"),
            Self::StrongDecrease => String::from("STRONG_DECREASE"),
            Self::AbsoluteDecrease => String::from("ABSOLUTE_DECREASE"),
        }
    }
}

impl Default for BiasDtoPeriodStrengthDto {
    fn default() -> BiasDtoPeriodStrengthDto {
        Self::AbsoluteIncrease
    }
}




