/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// BiasingProfileDto : Inline biasing profile, which should be applied to the search. Takes priority over biasing profile.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BiasingProfileDto {
    #[serde(rename = "biases")]
    pub biases: Vec<crate::models::BiasDto>,
}

impl BiasingProfileDto {
    /// Inline biasing profile, which should be applied to the search. Takes priority over biasing profile.
    pub fn new(biases: Vec<crate::models::BiasDto>) -> BiasingProfileDto {
        BiasingProfileDto {
            biases,
        }
    }
}


