/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BoostedProductBucket {
    #[serde(rename = "products")]
    pub products: Vec<String>,
}

impl BoostedProductBucket {
    pub fn new(products: Vec<String>) -> BoostedProductBucket {
        BoostedProductBucket {
            products,
        }
    }
}


