/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// DebugDto : Contains debug info associated to response.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DebugDto {
    /// Search request in raw format executed internally against search engine.
    #[serde(rename = "rawSearchRequest", skip_serializing_if = "Option::is_none")]
    pub raw_search_request: Option<Vec<serde_json::Value>>,
    /// Search response in raw format received internally from search engine.
    #[serde(rename = "rawSearchResponse", skip_serializing_if = "Option::is_none")]
    pub raw_search_response: Option<Vec<serde_json::Value>>,
}

impl DebugDto {
    /// Contains debug info associated to response.
    pub fn new() -> DebugDto {
        DebugDto {
            raw_search_request: None,
            raw_search_response: None,
        }
    }
}


