/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// ErrorResponse : Error object returned by the API.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Identifier used for tracking purposes.
    #[serde(rename = "trackingId")]
    pub tracking_id: String,
    /// HTTP method of the API call which produced the error.
    #[serde(rename = "method")]
    pub method: String,
    /// HTTP path of the API call which produced the error.
    #[serde(rename = "path")]
    pub path: String,
    /// Error message. Ideally human readable string.
    #[serde(rename = "message")]
    pub message: String,
}

impl ErrorResponse {
    /// Error object returned by the API.
    pub fn new(tracking_id: String, method: String, path: String, message: String) -> ErrorResponse {
        ErrorResponse {
            tracking_id,
            method,
            path,
            message,
        }
    }
}


