/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// FacetSearchResponseDto : Facet search response representation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetSearchResponseDto {
    #[serde(rename = "originalRequest")]
    pub original_request: Box<crate::models::SearchRequestDto>,
    #[serde(rename = "availableNavigation")]
    pub available_navigation: Box<crate::models::NavigationDto>,
}

impl FacetSearchResponseDto {
    /// Facet search response representation.
    pub fn new(original_request: crate::models::SearchRequestDto, available_navigation: crate::models::NavigationDto) -> FacetSearchResponseDto {
        FacetSearchResponseDto {
            original_request: Box::new(original_request),
            available_navigation: Box::new(available_navigation),
        }
    }
}


