/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// FacetSearchRequestDto : Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FacetSearchRequestDto {
    #[serde(rename = "facet")]
    pub facet: Box<crate::models::Facet>,
    #[serde(rename = "originalRequest")]
    pub original_request: Box<crate::models::SearchRequestDto>,
}

impl FacetSearchRequestDto {
    /// Request that should be populated to configure a search API call, made by the client on behalf of a shopper. Contains original request and information about facet for which extra keys requested.
    pub fn new(facet: crate::models::Facet, original_request: crate::models::SearchRequestDto) -> FacetSearchRequestDto {
        FacetSearchRequestDto {
            facet: Box::new(facet),
            original_request: Box::new(original_request),
        }
    }
}


