/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterParameter {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    #[serde(rename = "exclude")]
    pub exclude: bool,
    #[serde(rename = "derivedFromProduct")]
    pub derived_from_product: bool,
}

impl FilterParameter {
    pub fn new(field: String, exclude: bool, derived_from_product: bool) -> FilterParameter {
        FilterParameter {
            field,
            value: None,
            exclude,
            derived_from_product,
        }
    }
}


