/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// FulfillmentInfo : Fulfillment information, such as the store IDs for in-store pickup or region IDs for different shipping methods.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FulfillmentInfo {
    /// Fulfillment type. Place where product fulfilled.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Place ids where product fulfilled (array).
    #[serde(rename = "placeIds", skip_serializing_if = "Option::is_none")]
    pub place_ids: Option<Vec<String>>,
}

impl FulfillmentInfo {
    /// Fulfillment information, such as the store IDs for in-store pickup or region IDs for different shipping methods.
    pub fn new() -> FulfillmentInfo {
        FulfillmentInfo {
            r#type: None,
            place_ids: None,
        }
    }
}


