/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Identity {
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "company")]
    pub company: String,
    #[serde(rename = "roles")]
    pub roles: Vec<crate::models::Role>,
}

impl Identity {
    pub fn new(subject: String, company: String, roles: Vec<crate::models::Role>) -> Identity {
        Identity {
            subject,
            company,
            roles,
        }
    }
}


