/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Merchandiser {
    #[serde(rename = "merchandiserId")]
    pub merchandiser_id: String,
}

impl Merchandiser {
    pub fn new(merchandiser_id: String) -> Merchandiser {
        Merchandiser {
            merchandiser_id,
        }
    }
}


