/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageType {
    #[serde(rename = "UPDATE")]
    Update,
    #[serde(rename = "DELETE")]
    Delete,
    #[serde(rename = "CREATE")]
    Create,
    #[serde(rename = "UNRECOGNIZED")]
    Unrecognized,

}

impl ToString for MessageType {
    fn to_string(&self) -> String {
        match self {
            Self::Update => String::from("UPDATE"),
            Self::Delete => String::from("DELETE"),
            Self::Create => String::from("CREATE"),
            Self::Unrecognized => String::from("UNRECOGNIZED"),
        }
    }
}

impl Default for MessageType {
    fn default() -> MessageType {
        Self::Update
    }
}




