/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// Metadata : Area metadata used to store additional data from user in format field/value.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Metadata {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl Metadata {
    /// Area metadata used to store additional data from user in format field/value.
    pub fn new(key: String, value: String) -> Metadata {
        Metadata {
            key,
            value,
        }
    }
}


