/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// NavigationType : Type of navigation.

/// Type of navigation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NavigationType {
    #[serde(rename = "VALUE")]
    Value,
    #[serde(rename = "RANGE")]
    Range,

}

impl ToString for NavigationType {
    fn to_string(&self) -> String {
        match self {
            Self::Value => String::from("VALUE"),
            Self::Range => String::from("RANGE"),
        }
    }
}

impl Default for NavigationType {
    fn default() -> NavigationType {
        Self::Value
    }
}




