/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// NavigationTypeDto : Type of navigation.

/// Type of navigation.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum NavigationTypeDto {
    #[serde(rename = "Value")]
    Value,
    #[serde(rename = "Range")]
    Range,

}

impl ToString for NavigationTypeDto {
    fn to_string(&self) -> String {
        match self {
            Self::Value => String::from("Value"),
            Self::Range => String::from("Range"),
        }
    }
}

impl Default for NavigationTypeDto {
    fn default() -> NavigationTypeDto {
        Self::Value
    }
}




