/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// PageInfoDto : Information regarding where the page of results starts and ends.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PageInfoDto {
    /// Where in the list of products the page begins.
    #[serde(rename = "recordStart", skip_serializing_if = "Option::is_none")]
    pub record_start: Option<i64>,
    /// Where in the list of products the page ends.
    #[serde(rename = "recordEnd", skip_serializing_if = "Option::is_none")]
    pub record_end: Option<i64>,
}

impl PageInfoDto {
    /// Information regarding where the page of results starts and ends.
    pub fn new() -> PageInfoDto {
        PageInfoDto {
            record_start: None,
            record_end: None,
        }
    }
}


