/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinnedRefinement {
    #[serde(rename = "navigation")]
    pub navigation: String,
    #[serde(rename = "refinements")]
    pub refinements: Vec<crate::models::Refinement>,
}

impl PinnedRefinement {
    pub fn new(navigation: String, refinements: Vec<crate::models::Refinement>) -> PinnedRefinement {
        PinnedRefinement {
            navigation,
            refinements,
        }
    }
}


