/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceInfoPriceEffectiveTime {
    /// Timestamp seconds.
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i64>,
    /// Timestamp nanos.
    #[serde(rename = "nanos", skip_serializing_if = "Option::is_none")]
    pub nanos: Option<i32>,
}

impl PriceInfoPriceEffectiveTime {
    pub fn new() -> PriceInfoPriceEffectiveTime {
        PriceInfoPriceEffectiveTime {
            seconds: None,
            nanos: None,
        }
    }
}


