/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// PriceInfoPeriodPriceRange : The price range of all variant of product having the same primaryProductId



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceInfoPeriodPriceRange {
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<Box<crate::models::PriceInfoPriceRangePrice>>,
    #[serde(rename = "originalPrice", skip_serializing_if = "Option::is_none")]
    pub original_price: Option<Box<crate::models::PriceInfoPriceRangeOriginalPrice>>,
}

impl PriceInfoPeriodPriceRange {
    /// The price range of all variant of product having the same primaryProductId
    pub fn new() -> PriceInfoPeriodPriceRange {
        PriceInfoPeriodPriceRange {
            price: None,
            original_price: None,
        }
    }
}


