/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum QueryPatternTriggerPeriodType {
    #[serde(rename = "CONTAINS")]
    Contains,
    #[serde(rename = "ENDS_WITH")]
    EndsWith,
    #[serde(rename = "REGEX")]
    Regex,
    #[serde(rename = "STARTS_WITH")]
    StartsWith,
    #[serde(rename = "MATCHES")]
    Matches,

}

impl ToString for QueryPatternTriggerPeriodType {
    fn to_string(&self) -> String {
        match self {
            Self::Contains => String::from("CONTAINS"),
            Self::EndsWith => String::from("ENDS_WITH"),
            Self::Regex => String::from("REGEX"),
            Self::StartsWith => String::from("STARTS_WITH"),
            Self::Matches => String::from("MATCHES"),
        }
    }
}

impl Default for QueryPatternTriggerPeriodType {
    fn default() -> QueryPatternTriggerPeriodType {
        Self::Contains
    }
}




