/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Range {
    #[serde(rename = "low")]
    pub low: f64,
    #[serde(rename = "high")]
    pub high: f64,
}

impl Range {
    pub fn new(low: f64, high: f64) -> Range {
        Range {
            low,
            high,
        }
    }
}


