/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// Rating : The rating of this product.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Rating {
    /// The total number of ratings. This value is independent of the value of histogram.This value must be nonnegative.
    #[serde(rename = "ratingCount", skip_serializing_if = "Option::is_none")]
    pub rating_count: Option<i32>,
    /// The average rating of the product. The rating is scaled at 1-5.
    #[serde(rename = "averageRating", skip_serializing_if = "Option::is_none")]
    pub average_rating: Option<f32>,
    /// List of rating counts per rating value (index = rating - 1). The list is empty if there is no rating. If the list is non-empty, its size is always 5. For example, [41, 14, 13, 47, 303]. It means that the product got 41 ratings with 1 star, 14 ratings with 2 star, and so on.
    #[serde(rename = "ratingHistogram", skip_serializing_if = "Option::is_none")]
    pub rating_histogram: Option<Vec<i32>>,
}

impl Rating {
    /// The rating of this product.
    pub fn new() -> Rating {
        Rating {
            rating_count: None,
            average_rating: None,
            rating_histogram: None,
        }
    }
}


