/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// RecommendationsErrorResponse : Error returned by the API.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendationsErrorResponse {
    /// Identifier used for tracking purposes.
    #[serde(rename = "trackingId", skip_serializing_if = "Option::is_none")]
    pub tracking_id: Option<String>,
    /// HTTP method of the API call which produced the error.
    #[serde(rename = "method", skip_serializing_if = "Option::is_none")]
    pub method: Option<String>,
    /// HTTP path of the API call which produced the error.
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
    /// Error message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl RecommendationsErrorResponse {
    /// Error returned by the API.
    pub fn new() -> RecommendationsErrorResponse {
        RecommendationsErrorResponse {
            tracking_id: None,
            method: None,
            path: None,
            message: None,
        }
    }
}


