/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// RecordDto : Information regarding a product in the proprietary Group By API format.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordDto {
    /// Identifier of the record as an MD5 hash.
    #[serde(rename = "_id", skip_serializing_if = "Option::is_none")]
    pub _id: Option<String>,
    /// Logical URL of the record.
    #[serde(rename = "_u", skip_serializing_if = "Option::is_none")]
    pub _u: Option<String>,
    /// Title of the record.
    #[serde(rename = "_t", skip_serializing_if = "Option::is_none")]
    pub _t: Option<String>,
    /// Collection the record was queried from or resides.
    #[serde(rename = "collection", skip_serializing_if = "Option::is_none")]
    pub collection: Option<String>,
    /// All other metadata, read fields, the record has.
    #[serde(rename = "allMeta", skip_serializing_if = "Option::is_none")]
    pub all_meta: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl RecordDto {
    /// Information regarding a product in the proprietary Group By API format.
    pub fn new() -> RecordDto {
        RecordDto {
            _id: None,
            _u: None,
            _t: None,
            collection: None,
            all_meta: None,
        }
    }
}


