/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// RefinementDto : Refinement value or range in the navigation.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefinementDto {
    #[serde(rename = "type")]
    pub r#type: crate::models::NavigationTypeDto,
    /// Number of products which match this refinement value or range.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Value of the refinement.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Lower bound of the refinement range.
    #[serde(rename = "low", skip_serializing_if = "Option::is_none")]
    pub low: Option<f64>,
    /// Upper bound  of the refinement range.
    #[serde(rename = "high", skip_serializing_if = "Option::is_none")]
    pub high: Option<f64>,
}

impl RefinementDto {
    /// Refinement value or range in the navigation.
    pub fn new(r#type: crate::models::NavigationTypeDto) -> RefinementDto {
        RefinementDto {
            r#type,
            count: None,
            value: None,
            low: None,
            high: None,
        }
    }
}


