/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// Request : Object which is represent autocomplete request and encapsulate all passed parameters. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Request {
    /// Area i.e. 'Production' Will not be used immediately. This will be useful when we eventually need to support a US area vs a Canada area. But this would require using the custom dataset instead of user-generated.
    #[serde(rename = "area")]
    pub area: String,
    /// Name of the collection used to determine the retail backend to use. Usually it is name which is associated with retail project in command center (project configuration).
    #[serde(rename = "collection")]
    pub collection: String,
    /// Completion max suggestions. The maximum allowed max suggestions is 20.
    #[serde(rename = "searchItems")]
    pub search_items: i32,
    /// String. Required. The query used to generate suggestions. The maximum number of allowed characters is 255.
    #[serde(rename = "query")]
    pub query: String,
    /// Enable attribute suggestions, by setting the field enableAttributeSuggestion=true in the API request. Then in response, there will be an additional field attributeResults to show direct match results on brands/categories  Note that attribute results directly come from the products we import and Google does not apply any cleaning on them. 
    #[serde(rename = "enableAttributeSuggestion", skip_serializing_if = "Option::is_none")]
    pub enable_attribute_suggestion: Option<bool>,
    /// Optional param which is define if extended suggestions will be returned in autocomplete response or not. Possibly values: true, false, not specified (If not specified default collection setting will be used). 
    #[serde(rename = "extendedSuggestions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extended_suggestions: Option<Option<bool>>,
    ///     List with extended attributes which are would be returned in autocomplete response.     Requires extendedSuggestions to be enabled using search param or on collection layer. 
    #[serde(rename = "extendedAttributes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extended_attributes: Option<Option<Vec<String>>>,
    /// String. Not required field. A unique identifier for tracking visitors. For example, this could be implemented with an HTTP cookie, which should be able to uniquely identify a visitor on a single device. This unique identifier should not change if the visitor logs in or out of the website. The field must be a UTF-8 encoded string with a length limit of 128 characters. Otherwise, an INVALID_ARGUMENT error is returned. 
    #[serde(rename = "visitorId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub visitor_id: Option<Option<String>>,
    /// Name of site filter. If not specified, the specified area's default site will be applied if configured in Command Center. To not use default specify empty value i.e.\"\".  If the site doesn't exist then the search will execute without the site filter.
    #[serde(rename = "site", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub site: Option<Option<String>>,
}

impl Request {
    /// Object which is represent autocomplete request and encapsulate all passed parameters. 
    pub fn new(area: String, collection: String, search_items: i32, query: String) -> Request {
        Request {
            area,
            collection,
            search_items,
            query,
            enable_attribute_suggestion: None,
            extended_suggestions: None,
            extended_attributes: None,
            visitor_id: None,
            site: None,
        }
    }
}


