/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RuleType {
    #[serde(rename = "REGULAR")]
    Regular,
    #[serde(rename = "EXPERIMENT")]
    Experiment,

}

impl ToString for RuleType {
    fn to_string(&self) -> String {
        match self {
            Self::Regular => String::from("REGULAR"),
            Self::Experiment => String::from("EXPERIMENT"),
        }
    }
}

impl Default for RuleType {
    fn default() -> RuleType {
        Self::Regular
    }
}




