/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuleTemplateSection {
    #[serde(rename = "zoneId")]
    pub zone_id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "zoneContent")]
    pub zone_content: String,
    #[serde(rename = "zoneType")]
    pub zone_type: crate::models::ZoneType,
}

impl RuleTemplateSection {
    pub fn new(zone_id: i32, name: String, zone_content: String, zone_type: crate::models::ZoneType) -> RuleTemplateSection {
        RuleTemplateSection {
            zone_id,
            name,
            zone_content,
            zone_type,
        }
    }
}


