/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// SearchMetadataDto : Metadata relating to the search results, or how they were generated.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchMetadataDto {
    /// Token to assist beacon collectors in correlating searches to user events.
    #[serde(rename = "searchAttributionToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub search_attribution_token: Option<Option<String>>,
    /// Were the search results from a previous call.
    #[serde(rename = "cached", skip_serializing_if = "Option::is_none")]
    pub cached: Option<bool>,
    /// Total time spent performing the Google search in milliseconds.
    #[serde(rename = "totalTime", skip_serializing_if = "Option::is_none")]
    pub total_time: Option<i64>,
}

impl SearchMetadataDto {
    /// Metadata relating to the search results, or how they were generated.
    pub fn new() -> SearchMetadataDto {
        SearchMetadataDto {
            search_attribution_token: None,
            cached: None,
            total_time: None,
        }
    }
}


