/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchFilter {
    /// String to be appended to the search query.
    #[serde(rename = "value")]
    pub value: String,
}

impl SearchFilter {
    pub fn new(value: String) -> SearchFilter {
        SearchFilter {
            value,
        }
    }
}


