/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// SearchTerms : Object with one single suggestion and associated info (brands and categories).



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchTerms {
    /// Suggestion itself.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(rename = "additionalInfo")]
    pub additional_info: Box<crate::models::AdditionalInfo>,
}

impl SearchTerms {
    /// Object with one single suggestion and associated info (brands and categories).
    pub fn new(additional_info: crate::models::AdditionalInfo) -> SearchTerms {
        SearchTerms {
            value: None,
            additional_info: Box::new(additional_info),
        }
    }
}


