/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectedRefinementTrigger {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "range")]
    pub range: Box<crate::models::Range>,
    #[serde(rename = "type")]
    pub r#type: crate::models::SelectedRefinementTriggerPeriodType,
}

impl SelectedRefinementTrigger {
    pub fn new(field: String, value: String, range: crate::models::Range, r#type: crate::models::SelectedRefinementTriggerPeriodType) -> SelectedRefinementTrigger {
        SelectedRefinementTrigger {
            field,
            value,
            range: Box::new(range),
            r#type,
        }
    }
}


