/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SelectedRefinementTriggerPeriodType {
    #[serde(rename = "RANGE")]
    Range,
    #[serde(rename = "VALUE")]
    Value,
    #[serde(rename = "NAVIGATION_SELECTED")]
    NavigationSelected,

}

impl ToString for SelectedRefinementTriggerPeriodType {
    fn to_string(&self) -> String {
        match self {
            Self::Range => String::from("RANGE"),
            Self::Value => String::from("VALUE"),
            Self::NavigationSelected => String::from("NAVIGATION_SELECTED"),
        }
    }
}

impl Default for SelectedRefinementTriggerPeriodType {
    fn default() -> SelectedRefinementTriggerPeriodType {
        Self::Range
    }
}




