/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sort {
    /// Field the order will be applied to.
    #[serde(rename = "field")]
    pub field: String,
    /// OrderDto the products will appear in.
    #[serde(rename = "order", deserialize_with = "Option::deserialize")]
    pub order: Option<serde_json::Value>,
}

impl Sort {
    pub fn new(field: String, order: Option<serde_json::Value>) -> Sort {
        Sort {
            field,
            order,
        }
    }
}


