/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// SortDto : Order the returned products should appear on the page.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortDto {
    /// Field the order will be applied to.
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "order", deserialize_with = "Option::deserialize")]
    pub order: Option<crate::models::SortDtoPeriodOrderDto>,
}

impl SortDto {
    /// Order the returned products should appear on the page.
    pub fn new(field: String, order: Option<crate::models::SortDtoPeriodOrderDto>) -> SortDto {
        SortDto {
            field,
            order,
        }
    }
}


