/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// SortDtoPeriodOrderDto : Order the products will appear in

/// Order the products will appear in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortDtoPeriodOrderDto {
    #[serde(rename = "Ascending")]
    Ascending,
    #[serde(rename = "Descending")]
    Descending,

}

impl ToString for SortDtoPeriodOrderDto {
    fn to_string(&self) -> String {
        match self {
            Self::Ascending => String::from("Ascending"),
            Self::Descending => String::from("Descending"),
        }
    }
}

impl Default for SortDtoPeriodOrderDto {
    fn default() -> SortDtoPeriodOrderDto {
        Self::Ascending
    }
}




