/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpellCorrectionMode {
    #[serde(rename = "AUTO")]
    Auto,
    #[serde(rename = "SUGGESTION_ONLY")]
    SuggestionOnly,

}

impl ToString for SpellCorrectionMode {
    fn to_string(&self) -> String {
        match self {
            Self::Auto => String::from("AUTO"),
            Self::SuggestionOnly => String::from("SUGGESTION_ONLY"),
        }
    }
}

impl Default for SpellCorrectionMode {
    fn default() -> SpellCorrectionMode {
        Self::Auto
    }
}




