/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// TemplateDto : Template to assist the front end application in rendering the UI. Currently only the triggered rule name will be included, or the 'default' template name to indicate no rule was triggered. This is to mainly compatibility with the Searchandiser API and the addition of templates in the future. Template is search agnostic and do not affect search request or result. Templated selected only by triggered rule.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TemplateDto {
    /// Name of the template.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Name of the rule which may have triggered.
    #[serde(rename = "ruleName", skip_serializing_if = "Option::is_none")]
    pub rule_name: Option<String>,
    #[serde(rename = "triggerSet", skip_serializing_if = "Option::is_none")]
    pub trigger_set: Option<Box<crate::models::TemplateDtoTriggerSet>>,
    /// Zones for linked template.
    #[serde(rename = "zones", skip_serializing_if = "Option::is_none")]
    pub zones: Option<Vec<crate::models::ZoneDto>>,
}

impl TemplateDto {
    /// Template to assist the front end application in rendering the UI. Currently only the triggered rule name will be included, or the 'default' template name to indicate no rule was triggered. This is to mainly compatibility with the Searchandiser API and the addition of templates in the future. Template is search agnostic and do not affect search request or result. Templated selected only by triggered rule.
    pub fn new() -> TemplateDto {
        TemplateDto {
            name: None,
            rule_name: None,
            trigger_set: None,
            zones: None,
        }
    }
}


