/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// Timestamp : Timestamp info with seconds and nanos.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Timestamp {
    /// Timestamp seconds.
    #[serde(rename = "seconds", skip_serializing_if = "Option::is_none")]
    pub seconds: Option<i64>,
    /// Timestamp nanos.
    #[serde(rename = "nanos", skip_serializing_if = "Option::is_none")]
    pub nanos: Option<i32>,
}

impl Timestamp {
    /// Timestamp info with seconds and nanos.
    pub fn new() -> Timestamp {
        Timestamp {
            seconds: None,
            nanos: None,
        }
    }
}


