/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerSet {
    /// Query pattern triggers.
    #[serde(rename = "queryPatternTriggers")]
    pub query_pattern_triggers: Vec<crate::models::QueryPatternTrigger>,
    /// Selected refinement triggers.
    #[serde(rename = "selectedRefinementTriggers")]
    pub selected_refinement_triggers: Vec<crate::models::SelectedRefinementTrigger>,
    /// Custom parameter triggers.
    #[serde(rename = "customParameterTriggers")]
    pub custom_parameter_triggers: Vec<crate::models::CustomParameterTrigger>,
}

impl TriggerSet {
    pub fn new(query_pattern_triggers: Vec<crate::models::QueryPatternTrigger>, selected_refinement_triggers: Vec<crate::models::SelectedRefinementTrigger>, custom_parameter_triggers: Vec<crate::models::CustomParameterTrigger>) -> TriggerSet {
        TriggerSet {
            query_pattern_triggers,
            selected_refinement_triggers,
            custom_parameter_triggers,
        }
    }
}


