/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValueFilterPeriodValueFilterType {
    #[serde(rename = "TEXTUAL")]
    Textual,
    #[serde(rename = "NUMERIC")]
    Numeric,

}

impl ToString for ValueFilterPeriodValueFilterType {
    fn to_string(&self) -> String {
        match self {
            Self::Textual => String::from("TEXTUAL"),
            Self::Numeric => String::from("NUMERIC"),
        }
    }
}

impl Default for ValueFilterPeriodValueFilterType {
    fn default() -> ValueFilterPeriodValueFilterType {
        Self::Textual
    }
}




