/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValueFilter {
    /// Field the value applies to.
    #[serde(rename = "field")]
    pub field: String,
    /// Value to filter on.
    #[serde(rename = "value")]
    pub value: String,
    /// Numeric value to filter on.
    #[serde(rename = "numberValue")]
    pub number_value: f64,
    /// Describing whether the filter is negated or not: color that is NOT red.
    #[serde(rename = "exclude")]
    pub exclude: bool,
    /// Determine which field we need to use - value if 'TEXTUAL' type or numberValue if 'NUMERIC' type.
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
}

impl ValueFilter {
    pub fn new(field: String, value: String, number_value: f64, exclude: bool, r#type: Option<serde_json::Value>) -> ValueFilter {
        ValueFilter {
            field,
            value,
            number_value,
            exclude,
            r#type,
        }
    }
}


