/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */

/// ZoneDto : UI zones, that may contain code snippets, sub-searches and etc.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZoneDto {
    /// A name for the zone, ideally human-readable.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Box<crate::models::ZoneDtoType>>,
    /// Zone content - it is can be any data, HTML - code, usual text or etc
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Zone content - it is can be any data, HTML - code, usual text or etc
    #[serde(rename = "richContent", skip_serializing_if = "Option::is_none")]
    pub rich_content: Option<String>,
}

impl ZoneDto {
    /// UI zones, that may contain code snippets, sub-searches and etc.
    pub fn new() -> ZoneDto {
        ZoneDto {
            name: None,
            r#type: None,
            content: None,
            rich_content: None,
        }
    }
}


