/*
 * GroupBy Retail
 *
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * Contact: ops@groupbyinc.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ZoneType {
    #[serde(rename = "QUERY")]
    Query,
    #[serde(rename = "CONTENT")]
    Content,
    #[serde(rename = "RICH_CONTENT")]
    RichContent,
    #[serde(rename = "EXPECT_QUERY")]
    ExpectQuery,
    #[serde(rename = "GENERATED_CONTENT")]
    GeneratedContent,

}

impl ToString for ZoneType {
    fn to_string(&self) -> String {
        match self {
            Self::Query => String::from("QUERY"),
            Self::Content => String::from("CONTENT"),
            Self::RichContent => String::from("RICH_CONTENT"),
            Self::ExpectQuery => String::from("EXPECT_QUERY"),
            Self::GeneratedContent => String::from("GENERATED_CONTENT"),
        }
    }
}

impl Default for ZoneType {
    fn default() -> ZoneType {
        Self::Query
    }
}




